### ISSUE TITLE
Update Shine Get Timer description..

### ISSUE THREAD

**Issue by BitPatty** [BitPatty/gctGenerator#10]
...regarding load removals. I'd even prefer if the codes would be seperated but that's up to you

**Comment by QbeRoot** [comment]
I updated the description, but I think separating the codes would only make it more confusing, and the load removal code would make no sense on its own

**Comment by BitPatty** [comment]
I meant like having a timer that removes loads and one that doesn't - since there's existing leaderboards which use the original timing.

aka https://docs.google.com/spreadsheets/d/12wDUXjLqmcUuWSEXWc1fHNJc24KlfyCh0pvibZYEQM0/edit#gid=0

**Comment by QbeRoot** [comment]
The spreadsheet is the reason people wanted a loadless timer for more accurate comparison, it’ll be used on there now

**Comment by BitPatty** [comment]
Wasn't that only for the tourney?

**Comment by QbeRoot** [comment]
No, JP_Pal brought up the idea a few days before the tourney was announced

**Comment by BitPatty** [comment]
I see. Then I guess we're just gonna leave it for now.
